name: 'Get Tags Action'
description: 'Get Github tags from repo'
author: 'Omar Raad'
inputs:
  repo:
    required: true
    description: 'GitHub repo under <owner>/<repo> format'
  limit:
    description: 'Tags count'
    required: true
    default: '10'
  github-token:
    description: 'GitHub Token as provided by secrets'
    default: ${{ github.token }}
    required: true
outputs:
  tags:
    description: 'Tags JSON'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'tag'
  color: 'purple'
